print ('Cuantos libros tenes? ')
CantidadDeLibros = input ()
print ('cual es tu libro favorito? ')
LibroFavorito = input()
print ('de tus ' + CantidadDeLibros + ' libros, tu libro favorito es ' + LibroFavorito)
